// jenkinsfile config
pipeline {
    // 没有 agent 指令的话, 声明式流水线不仅无效, 它也不可能完成任何工作
    agent any
        // 使用全局定义工具
        tools {
            maven 'Maven 3.6.3'
            jdk 'JDK 1.8.0'
        }
        stages {
            stage('build') {
                steps {
                    echo 'Building..'
                    sh './jenkins/scripts/build.sh'
                }
            }
		    stage('Test') {
				steps {
                    echo 'Test..'
				}
			}
			stage('Deliver') {
				steps {
                    echo 'Deliver..'
				}
			}
        }
}		
